<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="com.hrms.testcases.AddEmployeeFromXLFile">
        <methods>
          <include name="AddEmployee"/>
          <include name="writeReport"/>
          <include name="generateReports"/>
          <include name="tearDown"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.hrms.testcases.AddEmployeeFromXLFile -->
      <class name="com.hrms.testcases.LoginPageTest">
        <methods>
          <include name="writeReport"/>
          <include name="generateReports"/>
          <include name="tearDown"/>
          <include name="multipleLogin" invocation-numbers="1 2"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.hrms.testcases.LoginPageTest -->
      <class name="com.hrms.testcases.DataDrivenTest">
        <methods>
          <include name="addEmployeeValidation" invocation-numbers="0"/>
          <include name="writeReport"/>
          <include name="generateReports"/>
          <include name="tearDown"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.hrms.testcases.DataDrivenTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
